### ISSUE TITLE
adding testnet

### ISSUE THREAD

**Issue by jack75015** [dcts/opensea-scraper#41] opened 2022-02-27 10:29 UTC
Hey
What could be nice is adding testnet option to scrap opensea testnet website :)

**Comment by dcts** [comment] 2022-02-27 14:23
Is it this one:
Testnets.opensea.io

Or are there more than 1 sotes?

**Comment by jack75015** [comment] 2022-02-27 14:26
yep this one
they use Rinkeby eth network

**Comment by dcts** [comment] 2022-03-17 22:49
@jack75015 is this still relevant to you? Because I tested and you can simply do this (as a "hack"):


```js
// TESTNET
const res = await OpenseaScraper.offersByUrl("https://testnets.opensea.io/collection/cyberbrokers-v3",options)
// => this gives you testnet results

// MAINNET
const res2 = await OpenseaScraper.offers("cyberbrokers-v3",options);
// => this gives you production results (empty) 
```

**Comment by dcts** [comment] 2022-04-02 00:56
closing as testnet scraping is already supported when using `offersByUrl` method.

**Comment by kaiqiangh** [comment] 2022-07-06 17:30
> 
Hi dcts,

I tried to use the same code to get results from opensea testnet, but it failed with the error message below.
![image](https://user-images.githubusercontent.com/9014062/177608922-95ceb0cd-39da-4515-b2c0-b7e7cb89c4b8.png)

It seems that the page is not actually scrapered so that there is no "html" content for further use. Any suggestions for that? 

Thanks.
Kai

**Comment by dcts** [comment] 2022-07-07 10:16
@kaiqiangh I could replicate the issue, the problem is the following:
- the testnet sites usually have a weird page that is displayed in between the actual result page
- just waiting for ~2 seconds before starting the scraping soloves the issue
- unfortunately there is no feature implemented to wait before scraping

I am working on a feature `additionalWait` where you can simply add to the options the number of milliseconds to wait before starting to scrape, which should fix the issue. 

will post soon once the feature is published on npm.

**Comment by kaiqiangh** [comment] 2022-07-07 10:23
Thank you very much!

**Comment by dcts** [comment] 2022-07-07 10:51
### new version with `additionalWait` just published (opensea-scraper v6.5.0) 

You should be able to overcome this issue like this:
1. upgrade to OpenseaScraper v6.5.0 (by running `npm install opensea-scraper@6.5.0`)
2. add an additionalWait of ~2-4 seconds:
```js
// TESTNET
const options = {
  additionalWait: 4000, // 4 seconds should work, you can try lowering that number
}
const res = await OpenseaScraper.offersByUrl("https://testnets.opensea.io/collection/cyberbrokers-v3",options)
// => this gives you testnet results
```

let me know if it worked :)

**Comment by kaiqiangh** [comment] 2022-07-07 11:09
Hi @dcts,

Much appreciated for your quick update.

It works, but there is a minor bug. 

![image](https://user-images.githubusercontent.com/9014062/177759553-d5e31713-7e3a-46bf-89b9-2479f3eb5922.png)

the offerURL should be llike "https://testnets.opensea.io/assets/rinkeby/NftAddress/nftID".

**Comment by dcts** [comment] 2022-07-07 11:27
Good catch, just fixed it! Please update to newest version:
```bash
npm install opensea-scraper@6.5.1
```

**Comment by dcts** [comment] 2022-07-07 11:39
great! Closing...!

**Closed by dcts** 2022-07-07 11:39 UTC
